In [3]:
import pandas as pd
import numpy as np

colors_raw = pd.read_csv(r"lego_data/colors.csv") 
colors = colors_raw.copy()

inventories_raw = pd.read_csv(r"lego_data/inventories.csv")
inventories = inventories_raw.copy()

inventory_parts_raw = pd.read_csv(r"lego_data/inventory_parts.csv")
inventory_parts = inventory_parts_raw.copy()

In [4]:
colors.head()

   id            name     rgb is_trans
0  -1         Unknown  0033B2        f
1   0           Black  05131D        f
2   1            Blue  0055BF        f
3   2           Green  237841        f
4   3  Dark Turquoise  008F9B        f

In [5]:
inventories.head()

   id  version set_num
0   1        1  7922-1
1   3        1  3931-1
2   4        1  6942-1
3  15        1  5158-1
4  16        1   903-1

In [7]:
inventory_parts.head()

   inventory_id     part_num  color_id  quantity is_spare
0             1     48379c01        72         1        f
1             1        48395         7         1        f
2             1     mcsport6        25         1        f
3             1       paddle         0         1        f
4             3  11816pr0005        78         1        f