In [1]:
import pandas as pd
import numpy as np

colors_raw = pd.read_csv(r"lego_data/colors.csv") 
colors = colors_raw.copy()

inventories_raw = pd.read_csv(r"lego_data/inventories.csv")
inventories = inventories_raw.copy()

inventory_parts_raw = pd.read_csv(r"lego_data/inventory_parts.csv")
inventory_parts = inventory_parts_raw.copy()

part_categories_raw = pd.read_csv(r"lego_data/part_categories.csv")
part_categories = part_categories_raw.copy()

parts_raw = pd.read_csv(r"lego_data/parts.csv")
parts = parts_raw.copy()

sets_raw = pd.read_csv(r"lego_data/sets.csv")
sets = sets_raw.copy()

themes_raw = pd.read_csv(r"lego_data/themes.csv") 
themes = themes_raw.copy()

In [2]:
colors.head()

   id            name     rgb is_trans
0  -1         Unknown  0033B2        f
1   0           Black  05131D        f
2   1            Blue  0055BF        f
3   2           Green  237841        f
4   3  Dark Turquoise  008F9B        f

In [3]:
inventories.head()

   id  version set_num
0   1        1  7922-1
1   3        1  3931-1
2   4        1  6942-1
3  15        1  5158-1
4  16        1   903-1

In [4]:
inventory_parts.head()

   inventory_id     part_num  color_id  quantity is_spare
0             1     48379c01        72         1        f
1             1        48395         7         1        f
2             1     mcsport6        25         1        f
3             1       paddle         0         1        f
4             3  11816pr0005        78         1        f

In [5]:
part_categories.head()

   id                     name
0   1               Baseplates
1   2           Bricks Printed
2   3            Bricks Sloped
3   4  Duplo, Quatro and Primo
4   5           Bricks Special

In [6]:
parts.head()

  part_num                                               name  part_cat_id
0   0687b1                        Set 0687 Activity Booklet 1           17
1     0901  Baseplate 16 x 30 with Set 080 Yellow House Print            1
2     0902  Baseplate 16 x 24 with Set 080 Small White Hou...            1
3     0903     Baseplate 16 x 24 with Set 080 Red House Print            1
4     0904  Baseplate 16 x 24 with Set 080 Large White Hou...            1

In [7]:
sets.head()

  set_num                        name  year  theme_id  num_parts
0    00-1             Weetabix Castle  1970       414        471
1  0011-2           Town Mini-Figures  1978        84         12
2  0011-3  Castle 2 for 1 Bonus Offer  1987       199          2
3  0012-1          Space Mini-Figures  1979       143         12
4  0013-1          Space Mini-Figures  1979       143         12

In [8]:
themes.head()

   id            name  parent_id
0   1         Technic        NaN
1   2  Arctic Technic        1.0
2   3     Competition        1.0
3   4  Expert Builder        1.0
4   5           Model        1.0

In [10]:
inventory_parts_with_color = pd.merge(inventory_parts, colors, how='left', left_on='color_id', right_on='id')
inventory_parts_with_parts = pd.merge(inventory_parts_with_color, parts, how='left', left_on='part_num', right_on='part_num')
inventory_parts_with_categories = pd.merge(inventory_parts_with_parts, part_categories, how='left', left_on='part_cat_id', right_on='id')
inventory_parts_with_categories.head()

,inventory_id,part_num,color_id,quantity,is_spare,id_x,name_x,rgb,is_trans,name_y,part_cat_id,id_y,name
0,1,48379c01,72,1,f,72,Dark Bluish Gray,6C6E68,f,Sports Promo Figure Base with Feet,27.0,27.0,Minifig Accessories
1,1,48395,7,1,f,7,Light Gray,9BA19D,f,Sports Promo Snowboard from McDonald's Sports ...,27.0,27.0,Minifig Accessories
2,1,mcsport6,25,1,f,25,Orange,FE8A18,f,Sports Promo Figure Head Torso Assembly McDona...,13.0,13.0,Minifigs
3,1,paddle,0,1,f,0,Black,05131D,f,Sports Promo Paddle from McDonald's Sports Sets,27.0,27.0,Minifig Accessories
4,3,11816pr0005,78,1,f,78,Light Flesh,F6D7B3,f,"Minifig Head Modified - Friends - Green Eyes, ...",13.0,13.0,Minifigs